//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptixiaki201
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallTAXI
    {
        public int Id { get; set; }
        public Nullable<int> NumOfCars { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> Room { get; set; }
    }
}
