//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptixiaki201
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyDataContainer : DbContext
    {
        public MyDataContainer()
            : base("name=MyDataContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Order> Order { get; set; }
        public DbSet<OrderFoodTab> OrderFoodTab { get; set; }
        public DbSet<Prosfores> Prosfores { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<Requests> Requests { get; set; }
        public DbSet<OrderWineTab> OrderWineTab { get; set; }
        public DbSet<CallTAXI> CallTAXI { get; set; }
        public DbSet<Administrator> Administrator { get; set; }
    }
}
