//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptixiaki201
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderWineTab
    {
        public int Id { get; set; }
        public string wineTitle { get; set; }
        public string wineCategory { get; set; }
        public string wineDescription { get; set; }
        public Nullable<double> winePrice { get; set; }
        public string Images { get; set; }
    }
}
