//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptixiaki201
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderFoodTab
    {
        public int Id { get; set; }
        public string foodTitle { get; set; }
        public string foodCategory { get; set; }
        public string foodDescription { get; set; }
        public double foodPrice { get; set; }
        public Nullable<int> foodIndexofPage { get; set; }
        public Nullable<double> foodOverallPrice { get; set; }
        public string Images { get; set; }
    }
}
