//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptixiaki201
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prosfores
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<double> OriginalPrice { get; set; }
        public Nullable<double> PriceWithDiscount { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public string Category { get; set; }
        public Nullable<bool> TopOffer { get; set; }
    }
}
