//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptixiaki201
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int Id { get; set; }
        public string RequestBody { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Room { get; set; }
    
        public virtual Requests Requests1 { get; set; }
        public virtual Requests Requests2 { get; set; }
    }
}
